modLoader = "kotlinforforge"
loaderVersion = "[5.10,)"
license = "MIT"

[[mods]]
modId = "ziangts"
version = "${version}"
displayName = "Zian GTS"
authors = "ZIANBLK"
description = "Sistema GTS para Cobblemon, desarrollado para Aventura."

[[dependencies.ziangts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.ziangts]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.228,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ziangts]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.8.0+1.21.1,)"
ordering = "AFTER"
side = "BOTH"


[[dependencies.ziangts]]
modId = "avecoins"
type = "required"
versionRange = "[2.3,2.4)"
ordering = "AFTER"
side = "BOTH"
